### ISSUE TITLE
Syntax error "else" unexpected (expecting "then")

### ISSUE THREAD

**Issue by DerAlSem** [aire1/mtproxy_autoinstaller#2]
root@vpn:~/mtproxy_autoinstaller# ./install.sh mynewsecret123
./install.sh: 104: ./install.sh: Syntax error: "else" unexpected (expecting "then")
root@vpn:~/mtproxy_autoinstaller# ./install.sh
./install.sh: 104: ./install.sh: Syntax error: "else" unexpected (expecting "then")
root@vpn:~/mtproxy_autoinstaller#

**Comment by aire1** [comment]
fixed, thanks for your report

**Comment by soranerai** [comment]
fixed, thanks for your report
